# Generated by Django 5.1 on 2024-08-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AlterField(
            model_name="tournament",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
